# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatApplication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chatApplication.proto',
  package='chatApp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63hatApplication.proto\x12\x07\x63hatApp\".\n\x0bUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\x12\x43reateUserResponse\x12\x11\n\tisCreated\x18\x01 \x01(\x08\",\n\x19VerifyCredentialsResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\"K\n\x14\x43reateMessageRequest\x12\"\n\x04user\x18\x01 \x01(\x0b\x32\x14.chatApp.UserRequest\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\x15\x43reateMessageResponse\x12\x11\n\tisCreated\x18\x01 \x01(\x08\"1\n\x0fMessageResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb2\x02\n\x0f\x43hatApplication\x12?\n\nCreateUser\x12\x14.chatApp.UserRequest\x1a\x1b.chatApp.CreateUserResponse\x12M\n\x11VerifyCredentials\x12\x14.chatApp.UserRequest\x1a\".chatApp.VerifyCredentialsResponse\x12N\n\rCreateMessage\x12\x1d.chatApp.CreateMessageRequest\x1a\x1e.chatApp.CreateMessageResponse\x12?\n\x0bGetMessages\x12\x14.chatApp.UserRequest\x1a\x18.chatApp.MessageResponse0\x01\x62\x06proto3'
)




_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='chatApp.UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='chatApp.UserRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='chatApp.UserRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=80,
)


_CREATEUSERRESPONSE = _descriptor.Descriptor(
  name='CreateUserResponse',
  full_name='chatApp.CreateUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isCreated', full_name='chatApp.CreateUserResponse.isCreated', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=121,
)


_VERIFYCREDENTIALSRESPONSE = _descriptor.Descriptor(
  name='VerifyCredentialsResponse',
  full_name='chatApp.VerifyCredentialsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isValid', full_name='chatApp.VerifyCredentialsResponse.isValid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=167,
)


_CREATEMESSAGEREQUEST = _descriptor.Descriptor(
  name='CreateMessageRequest',
  full_name='chatApp.CreateMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='chatApp.CreateMessageRequest.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='chatApp.CreateMessageRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=244,
)


_CREATEMESSAGERESPONSE = _descriptor.Descriptor(
  name='CreateMessageResponse',
  full_name='chatApp.CreateMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isCreated', full_name='chatApp.CreateMessageResponse.isCreated', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=288,
)


_MESSAGERESPONSE = _descriptor.Descriptor(
  name='MessageResponse',
  full_name='chatApp.MessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='chatApp.MessageResponse.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='chatApp.MessageResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=339,
)

_CREATEMESSAGEREQUEST.fields_by_name['user'].message_type = _USERREQUEST
DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['CreateUserResponse'] = _CREATEUSERRESPONSE
DESCRIPTOR.message_types_by_name['VerifyCredentialsResponse'] = _VERIFYCREDENTIALSRESPONSE
DESCRIPTOR.message_types_by_name['CreateMessageRequest'] = _CREATEMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['CreateMessageResponse'] = _CREATEMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'chatApplication_pb2'
  # @@protoc_insertion_point(class_scope:chatApp.UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

CreateUserResponse = _reflection.GeneratedProtocolMessageType('CreateUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERRESPONSE,
  '__module__' : 'chatApplication_pb2'
  # @@protoc_insertion_point(class_scope:chatApp.CreateUserResponse)
  })
_sym_db.RegisterMessage(CreateUserResponse)

VerifyCredentialsResponse = _reflection.GeneratedProtocolMessageType('VerifyCredentialsResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYCREDENTIALSRESPONSE,
  '__module__' : 'chatApplication_pb2'
  # @@protoc_insertion_point(class_scope:chatApp.VerifyCredentialsResponse)
  })
_sym_db.RegisterMessage(VerifyCredentialsResponse)

CreateMessageRequest = _reflection.GeneratedProtocolMessageType('CreateMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEMESSAGEREQUEST,
  '__module__' : 'chatApplication_pb2'
  # @@protoc_insertion_point(class_scope:chatApp.CreateMessageRequest)
  })
_sym_db.RegisterMessage(CreateMessageRequest)

CreateMessageResponse = _reflection.GeneratedProtocolMessageType('CreateMessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEMESSAGERESPONSE,
  '__module__' : 'chatApplication_pb2'
  # @@protoc_insertion_point(class_scope:chatApp.CreateMessageResponse)
  })
_sym_db.RegisterMessage(CreateMessageResponse)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'chatApplication_pb2'
  # @@protoc_insertion_point(class_scope:chatApp.MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)



_CHATAPPLICATION = _descriptor.ServiceDescriptor(
  name='ChatApplication',
  full_name='chatApp.ChatApplication',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=342,
  serialized_end=648,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateUser',
    full_name='chatApp.ChatApplication.CreateUser',
    index=0,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_CREATEUSERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='VerifyCredentials',
    full_name='chatApp.ChatApplication.VerifyCredentials',
    index=1,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_VERIFYCREDENTIALSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateMessage',
    full_name='chatApp.ChatApplication.CreateMessage',
    index=2,
    containing_service=None,
    input_type=_CREATEMESSAGEREQUEST,
    output_type=_CREATEMESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMessages',
    full_name='chatApp.ChatApplication.GetMessages',
    index=3,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_MESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATAPPLICATION)

DESCRIPTOR.services_by_name['ChatApplication'] = _CHATAPPLICATION

# @@protoc_insertion_point(module_scope)
